# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticles',
            new_name='NewsArticle',
        ),
    ]
