# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161114_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='img_src',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
