# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20161114_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='img_src',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='post_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
