# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20161118_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name=b'date registered')),
                ('ip', models.CharField(max_length=16)),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
            ],
        ),
    ]
