# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_fcmdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FcmDetails',
            new_name='User',
        ),
    ]
